name: 'Chromatic'

on: push

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn
      - name: Publish to Chromatic
        uses: mansagroup/nrwl-nx-action@v2
        with:
          targets: chromatic
          projects: zoopi-web
          env:
            CHROMATIC_PROJECT_TOKEN: secrets.CHROMATIC_PROJECT_TOKEN
